<a href="https://colab.research.google.com/github/thamindu19/CS4622-Lab1/blob/main/190316H_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dataframe_train = pd.read_csv('train.csv')
dataframe_test = pd.read_csv('test.csv')
dataframe_valid = pd.read_csv('valid.csv')
dataframe_train.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.928826  -0.291540   1.105909   2.070652   0.657838  -0.670940   
1  -1.709277  -1.008998   0.956611   4.313823  -0.669455   1.928765   
2  -1.906183  -0.357562  -0.682627   4.651838  -0.884940   1.159512   
3   0.697872  -2.218567  -0.572214   1.192062   0.329554   0.741364   
4  -1.976895  -0.496308   0.368102   3.739787  -0.132058   1.234980   

   feature_7  feature_8  feature_9  feature_10  ...  feature_251  feature_252  \
0  -0.968238   0.049916   1.111149   -1.834592  ...    -0.691538    -1.152522   
1   0.162550   0.152173   2.356505   -2.898549  ...    -0.668235    -0.532695   
2   1.354481  -1.432248   2.160144   -3.175735  ...    -0.026728     0.440408   
3   0.962354   0.993512   2.896854   -1.600380  ...     0.709032     0.812106   
4  -0.501003   0.881554   1.630941   -3.853953  ...    -0.599700    -1.024829   

   feature_253  feature_254  feature_255  feature_256  label_1  label_2  \
0     0.441157    -1.494434    -0.344974    -0.395641       45      NaN   
1     0.151163    -1.876885     1.651534    -2.706490       45      NaN   
2     2.745906    -0.680754    -0.643588    -2.587203       45      NaN   
3     1.055266    -0.915258    -0.924856    -1.318964       45      NaN   
4     1.869753    -2.498570     3.268253    -1.356606       45      NaN   

   label_3  label_4  
0        1        6  
1        1        6  
2        1        6  
3        1        6  
4        1        6  

[5 rows x 260 columns]

In [ ]:
dataframe_train.info()
dataframe_train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28520 entries, 0 to 28519
Columns: 260 entries, feature_1 to label_4
dtypes: float64(257), int64(3)
memory usage: 56.6 MB


feature_1     feature_2     feature_3     feature_4     feature_5  \
count  28520.000000  28520.000000  28520.000000  28520.000000  28520.000000   
mean      -0.225478     -0.616421     -0.212878      0.336330      0.105467   
std        0.990632      1.005573      1.075468      1.248919      0.831132   
min       -4.023911     -5.582544     -4.679888     -4.284380     -3.010300   
25%       -0.869656     -1.287018     -0.913419     -0.478661     -0.437171   
50%       -0.190790     -0.609782     -0.218800      0.295881      0.117310   
75%        0.457509      0.063174      0.490262      1.119242      0.657941   
max        4.322171      3.876604      4.267163      5.828656      3.884939   

          feature_6     feature_7     feature_8     feature_9    feature_10  \
count  28520.000000  28520.000000  28520.000000  28520.000000  28520.000000   
mean      -0.339634     -0.201756      0.742262      0.942325     -1.957584   
std        1.073267      0.943505      1.055721      0.940459      0.876939   
min       -5.034355     -4.355222     -3.806574     -2.922614     -5.203347   
25%       -1.075753     -0.823699      0.064072      0.298269     -2.556436   
50%       -0.329571     -0.193263      0.755193      0.940786     -1.949847   
75%        0.393339      0.417146      1.461846      1.579200     -1.345999   
max        3.890622      3.799406      4.817545      4.615069      1.147192   

       ...   feature_251   feature_252   feature_253   feature_254  \
count  ...  28520.000000  28520.000000  28520.000000  28520.000000   
mean   ...     -0.028098      0.296340      1.724439     -1.476765   
std    ...      0.989497      1.173378      0.968611      1.032811   
min    ...     -3.679602     -3.905801     -3.301683     -5.490267   
25%    ...     -0.692262     -0.550897      1.121631     -2.130906   
50%    ...     -0.018218      0.295523      1.783432     -1.449978   
75%    ...      0.644112      1.128566      2.383575     -0.799414   
max    ...      3.915582      4.458014      5.261775      2.861117   

        feature_255   feature_256       label_1       label_2       label_3  \
count  28520.000000  28520.000000  28520.000000  28040.000000  28520.000000   
mean       0.687445     -1.563062     30.498843     27.975107      0.799299   
std        1.028328      1.243758     17.328389      5.735913      0.400532   
min       -3.810144     -6.056032      1.000000     22.000000      0.000000   
25%       -0.008394     -2.404028     15.000000     25.000000      1.000000   
50%        0.639575     -1.650610     30.000000     27.000000      1.000000   
75%        1.347263     -0.805710     46.000000     30.000000      1.000000   
max        5.531152      3.338544     60.000000     61.000000      1.000000   

            label_4  
count  28520.000000  
mean       5.997125  
std        2.375567  
min        0.000000  
25%        6.000000  
50%        6.000000  
75%        6.000000  
max       13.000000  

[8 rows x 260 columns]

In [ ]:
from sklearn.preprocessing import RobustScaler

LABELS = [F'label_{i}' for i in range(1, 5)]
FEATURES = [F'feature_{i}' for i in range(1, 257)]

X_train, X_valid, X_test, y_train, y_valid, y_predict, y_test_1, y_test_2 = [{} for _ in range(8)]


for label in LABELS:
    if label == 'label_2':
        df_train = dataframe_train[dataframe_train['label_2'].notna()]
        df_valid = dataframe_valid[dataframe_valid['label_2'].notna()]
    else:
        df_train = dataframe_train
        df_valid = dataframe_valid
    df_test = dataframe_test

    scaler = RobustScaler()
    X_train[label] = pd.DataFrame(scaler.fit_transform(df_train.drop(LABELS, axis=1)), columns=FEATURES)
    y_train[label] = df_train[label]
    X_valid[label] = pd.DataFrame(scaler.transform(df_valid.drop(LABELS, axis=1)), columns=FEATURES)
    y_valid[label] = df_valid[label]
    X_test[label] = df_test.drop(LABELS, axis=1)

In [ ]:
X_train['label_1'].head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.309586   0.235701   0.943739   1.110687   0.493583  -0.232368   
1  -1.144159  -0.295674   0.837377   2.514509  -0.718433   1.537233   
2  -1.292525   0.186803  -0.330437   2.726045  -0.915203   1.013608   
3   0.669594  -1.191524  -0.251777   0.560848   0.193810   0.728978   
4  -1.345805   0.084043   0.418116   2.155265  -0.227710   1.064978   

   feature_7  feature_8  feature_9  feature_10  ...  feature_247  feature_248  \
0  -0.624554  -0.504571   0.132999    0.095217  ...     1.583006     1.101137   
1   0.286751  -0.431414   1.105227   -0.783768  ...     1.036040    -0.688550   
2   1.247330  -1.564947   0.951931   -1.012765  ...     0.297848     0.303437   
3   0.931314   0.170499   1.527067    0.288711  ...     0.829376    -0.102070   
4  -0.248008   0.090402   0.538791   -1.573073  ...     1.058010    -0.117040   

   feature_249  feature_250  feature_251  feature_252  feature_253  \
0    -0.786061     0.622750    -0.503841    -0.862208    -1.063657   
1    -1.640606    -0.053767    -0.486404    -0.493145    -1.293456   
2    -2.323521    -0.182392    -0.006368     0.086269     0.762691   
3    -2.596694    -0.616500     0.544197     0.307588    -0.577020   
4    -1.419770     0.362046    -0.435119    -0.786176     0.068403   

   feature_254  feature_255  feature_256  
0    -0.033389    -0.726253     0.785181  
1    -0.320623     0.746471    -0.660619  
2     0.577715    -0.946525    -0.585987  
3     0.401594    -1.154003     0.207497  
4    -0.787532     1.939043     0.183946  

[5 rows x 256 columns]

In [ ]:
y_train['label_2']

480      25.0
481      25.0
482      25.0
483      25.0
484      25.0
         ... 
28515    29.0
28516    29.0
28517    29.0
28518    29.0
28519    29.0
Name: label_2, Length: 28040, dtype: float64

In [ ]:
from sklearn import svm, metrics

clf = svm.SVC(kernel='linear')
clf.fit(X_train['label_1'], y_train['label_1'])

y_predict['label_1'] = clf.predict(X_valid['label_1'])

print(metrics.confusion_matrix(y_valid['label_1'], y_predict['label_1']))
print(metrics.accuracy_score(y_valid['label_1'], y_predict['label_1']))
print(metrics.precision_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))
print(metrics.recall_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9906666666666667
0.9914608132608133
0.9906666666666667


In [ ]:
clf = svm.SVC(kernel='linear')
clf.fit(X_train['label_1'], y_train['label_1'])
y_test_1['label_1'] = clf.predict(X_test['label_1'])

clf = svm.SVC(kernel='linear')
clf.fit(X_train['label_2'], y_train['label_2'])
y_test_1['label_2'] = clf.predict(X_test['label_2'])

clf = svm.SVC(kernel='linear')
clf.fit(X_train['label_3'], y_train['label_3'])
y_test_1['label_3'] = clf.predict(X_test['label_3'])

clf = svm.SVC(kernel='linear', class_weight='balanced')
clf.fit(X_train['label_4'], y_train['label_4'])
y_test_1['label_4'] = clf.predict(X_test['label_4'])

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(f_classif, k=100)
X_select = selector.fit_transform(X_train['label_1'], y_train['label_1'])
print("Shape: ", X_select.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_select, y_train['label_1'])

y_predict['label_1'] = clf.predict(selector.transform(X_valid['label_1']))
print(metrics.confusion_matrix(y_valid['label_1'], y_predict['label_1']))
print(metrics.accuracy_score(y_valid['label_1'], y_predict['label_1']))
print(metrics.precision_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))
print(metrics.recall_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))

Shape:  (28520, 100)
[[12  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  9]]
0.976
0.9774185666185666
0.976


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95, svd_solver='full')
pca.fit(X_train['label_1'])
X_train_ldr = pd.DataFrame(pca.transform(X_train['label_1']))
X_valid_ldr = pd.DataFrame(pca.transform(X_valid['label_1']))
X_test_ldr = pd.DataFrame(pca.transform(X_test['label_1']))
print("Shape: ", X_train_ldr.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_train_ldr, y_train['label_1'])

y_predict['label_1'] = clf.predict(X_valid_ldr)

print(metrics.confusion_matrix(y_valid['label_1'], y_predict['label_1']))
print(metrics.accuracy_score(y_valid['label_1'], y_predict['label_1']))
print(metrics.precision_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))
print(metrics.recall_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))

Shape:  (28520, 67)
[[12  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9786666666666667
0.9809336030784948
0.9786666666666667


In [ ]:
selector = SelectKBest(f_classif, k=50)
X_select = selector.fit_transform(X_train_ldr, y_train['label_1'])
print("Shape: ", X_select.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_select, y_train['label_1'])

y_predict['label_1'] = clf.predict(selector.transform(X_valid_ldr))
X_label_1 = selector.transform(X_test_ldr)
y_test_2['label_1'] = clf.predict(X_label_1)

print(metrics.confusion_matrix(y_valid['label_1'], y_predict['label_1']))
print(metrics.accuracy_score(y_valid['label_1'], y_predict['label_1']))
print(metrics.precision_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))
print(metrics.recall_score(y_valid['label_1'], y_predict['label_1'], average='weighted'))

Shape:  (28520, 50)
[[10  0  0 ...  0  0  0]
 [ 0  7  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  9]]
0.96
0.9623806562661052
0.96


In [ ]:
pca = PCA(n_components=0.999, svd_solver='full')
pca.fit(X_train['label_2'])
X_train_ldr = pd.DataFrame(pca.transform(X_train['label_2']))
X_valid_ldr = pd.DataFrame(pca.transform(X_valid['label_2']))
X_test_ldr = pd.DataFrame(pca.transform(X_test['label_2']))
print("Shape: ", X_train_ldr.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_train_ldr, y_train['label_2'])

y_predict['label_2'] = clf.predict(X_valid_ldr)

selector = SelectKBest(f_classif, k=150)
X_select = selector.fit_transform(X_train_ldr, y_train['label_2'])
print("Shape: ", X_select.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_select, y_train['label_2'])

y_predict['label_2'] = clf.predict(selector.transform(X_valid_ldr))
X_label_2 = selector.transform(X_test_ldr)
y_test_2['label_2'] = clf.predict(X_label_2)

print(metrics.confusion_matrix(y_valid['label_2'], y_predict['label_2']))
print(metrics.accuracy_score(y_valid['label_2'], y_predict['label_2']))
print(metrics.precision_score(y_valid['label_2'], y_predict['label_2'], average='weighted'))
print(metrics.recall_score(y_valid['label_2'], y_predict['label_2'], average='weighted'))

Shape:  (28040, 167)
Shape:  (28040, 150)
[[ 33   0   0   0   1   1   1   0   0   0   0   0   0   0   0   0   0]
 [  1  63   1   2   2   0   1   0   1   0   0   0   0   0   0   0   0]
 [  0   1  42   0   2   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   9   1  63   2   1   0   0   3   0   0   0   0   0   0   0   0]
 [  0   4   3   2 101   2   0   1   1   1   0   0   0   0   0   0   0]
 [  0   3   4   0   4  63   0   1   2   3   0   0   1   0   0   0   0]
 [  0   0   1   0   2   2  41   0   0   0   0   0   0   0   0   0   0]
 [  3   0   0   0   1   0   0  41   0   0   0   0   0   0   0   0   0]
 [  0   1   0   2   1   2   0   0  41   1   0   0   0   0   0   0   0]
 [  1   2   1   2   1   3   1   0   1  51   2   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0   0   0  29   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  11   0   0   0   0]
 [  0   0   0   0   0   0   0   0  

In [ ]:
pca = PCA(n_components=0.90, svd_solver='full')
pca.fit(X_train['label_3'])
X_train_ldr = pd.DataFrame(pca.transform(X_train['label_3']))
X_valid_ldr = pd.DataFrame(pca.transform(X_valid['label_3']))
X_test_ldr = pd.DataFrame(pca.transform(X_test['label_3']))
print("Shape: ", X_train_ldr.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_train_ldr, y_train['label_3'])

selector = SelectKBest(f_classif, k=5)
X_select = selector.fit_transform(X_train_ldr, y_train['label_3'])
print("Shape: ", X_select.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_select, y_train['label_3'])

y_predict['label_3'] = clf.predict(selector.transform(X_valid_ldr))
X_label_3 = selector.transform(X_test_ldr)
y_test_2['label_3'] = clf.predict(X_label_3)

print(metrics.confusion_matrix(y_valid['label_3'], y_predict['label_3']))
print(metrics.accuracy_score(y_valid['label_3'], y_predict['label_3']))
print(metrics.precision_score(y_valid['label_3'], y_predict['label_3'], average='weighted'))
print(metrics.recall_score(y_valid['label_3'], y_predict['label_3'], average='weighted'))

Shape:  (28520, 49)
Shape:  (28520, 5)
[[133   9]
 [  6 602]]
0.98
0.9798862579330971
0.98


In [ ]:
pca = PCA(n_components=0.90, svd_solver='full')
pca.fit(X_train['label_4'])
X_train_ldr = pd.DataFrame(pca.transform(X_train['label_4']))
X_valid_ldr = pd.DataFrame(pca.transform(X_valid['label_4']))
X_test_ldr = pd.DataFrame(pca.transform(X_test['label_4']))
print("Shape: ", X_train_ldr.shape)

clf = svm.SVC(kernel='linear', class_weight='balanced')
clf.fit(X_train_ldr, y_train['label_4'])

selector = SelectKBest(f_classif, k=37)
X_select = selector.fit_transform(X_train_ldr, y_train['label_4'])
print("Shape: ", X_select.shape)

clf = svm.SVC(kernel='linear')
clf.fit(X_select, y_train['label_4'])

y_predict['label_4'] = clf.predict(selector.transform(X_valid_ldr))
X_label_4 = selector.transform(X_test_ldr)
y_test_2['label_4'] = clf.predict(X_label_4)

print(metrics.confusion_matrix(y_valid['label_4'], y_predict['label_4']))
print(metrics.accuracy_score(y_valid['label_4'], y_predict['label_4']))
print(metrics.precision_score(y_valid['label_4'], y_predict['label_4'], average='weighted'))
print(metrics.recall_score(y_valid['label_4'], y_predict['label_4'], average='weighted'))

Shape:  (28520, 49)
Shape:  (28520, 37)
[[  9   0   1   0   0   0  10   1   0   0   0   0   0   0]
 [  0   5   0   0   0   0   6   0   0   0   0   0   0   0]
 [  1   0  14   0   0   0  12   0   0   0   0   0   0   0]
 [  0   0   0   7   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0  10   0   5   0   0   0   0   0   0   0]
 [  0   0   0   0   0  11   0   0   0   0   0   0   0   0]
 [  1   0   4   1   0   1 523   0   2   0   0   0   0   0]
 [  0   0   0   0   1   0  22   9   0   0   0   0   0   0]
 [  0   0   0   0   0   0   5   0  14   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0  16   0   0   0   0]
 [  0   0   0   0   0   0   5   0   0   0   5   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  11   0   0]
 [  0   0   0   0   0   0  19   2   0   0   0   0   5   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   9]]
0.864
0.8660611228767398
0.864


In [ ]:
import numpy as np

csv_label_1 = np.column_stack([np.transpose(y_test_1['label_1']), np.transpose(y_test_2['label_1']), [len(X_label_1[0])] * len(y_test_1['label_1']), X_label_1])
csv_label_2 = np.column_stack([np.transpose(y_test_1['label_2']), np.transpose(y_test_2['label_2']), [len(X_label_2[0])] * len(y_test_1['label_2']), X_label_2])
csv_label_3 = np.column_stack([np.transpose(y_test_1['label_3']), np.transpose(y_test_2['label_3']), [len(X_label_3[0])] * len(y_test_1['label_3']), X_label_3])
csv_label_4 = np.column_stack([np.transpose(y_test_1['label_4']), np.transpose(y_test_2['label_4']), [len(X_label_4[0])] * len(y_test_1['label_4']), X_label_4])

np.savetxt('out.csv', csv_label_1, delimiter=',', fmt='%d')
with open('190316H_label_1.csv', 'a') as file:
    with open('out.csv', 'r') as temp_file:
        file.write(temp_file.read())

np.savetxt('out.csv', csv_label_2, delimiter=',', fmt='%d')
with open('190316H_label_2.csv', 'a') as file:
    with open('out.csv', 'r') as temp_file:
        file.write(temp_file.read())

np.savetxt('out.csv', csv_label_3, delimiter=',', fmt='%d')
with open('190316H_label_3.csv', 'a') as file:
    with open('out.csv', 'r') as temp_file:
        file.write(temp_file.read())

np.savetxt('out.csv', csv_label_4, delimiter=',', fmt='%d')
with open('190316H_label_4.csv', 'a') as file:
    with open('out.csv', 'r') as temp_file:
        file.write(temp_file.read())

import os
os.remove('out.csv')
